/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useMemo } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils';
import { useSelector } from 'react-redux';

export default function Model({ ...props }) {
    const player = useSelector((state) => state.players[props.playerId]);
    const group = useRef();
    const { scene, materials, animations } = useGLTF('/models/playerModels/aj.glb');
    const clones = useMemo(() => clone(scene), [scene]);
    const { nodes } = useGraph(clones);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        actions.Idle.play();
    }, []);
    useEffect(() => {
        if (!player.animation) return;
        switch (player.animation) {
            case 'Jumping':
                actions.Idle.stop();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Jumping.play();
                break;
            case 'Walking_forward':
                actions.Walking_forward.play();
                actions.Walking_backward.stop();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Walking_left':
                actions.Walking_left.play();
                actions.Walking_right.stop();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Walking_right':
                actions.Walking_right.play();
                actions.Walking_left.stop();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Walking_backward':
                actions.Walking_backward.play();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Walking_forward.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Running_forward':
                actions.Running_forward.play();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Running_backward.stop();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Running_left':
                actions.Running_left.play();
                actions.Running_right.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Running_right':
                actions.Running_right.play();
                actions.Running_left.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Running_backward':
                actions.Running_backward.play();
                actions.Running_forward.stop();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Idle.stop();
                actions.Jumping.stop();
                break;
            case 'Idle':
                actions.Idle.play();
                actions.Walking_forward.stop();
                actions.Walking_backward.stop();
                actions.Walking_right.stop();
                actions.Walking_left.stop();
                actions.Running_forward.stop();
                actions.Running_backward.stop();
                actions.Running_right.stop();
                actions.Running_left.stop();
                actions.Jumping.stop();
                break;
            default:
                break;
        }
    }, [player.animation]);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <primitive object={nodes.Hips} />
                    <skinnedMesh
                        name="Boy01_Body_Geo"
                        geometry={nodes.Boy01_Body_Geo.geometry}
                        material={materials.Boy01_Body_MAT}
                        skeleton={nodes.Boy01_Body_Geo.skeleton}
                    />
                    <skinnedMesh
                        name="Boy01_Brows_Geo"
                        geometry={nodes.Boy01_Brows_Geo.geometry}
                        material={materials.Boy01_Brows_MAT1}
                        skeleton={nodes.Boy01_Brows_Geo.skeleton}
                    />
                    <skinnedMesh
                        name="Boy01_Eyes_Geo"
                        geometry={nodes.Boy01_Eyes_Geo.geometry}
                        material={materials.Boy01_Eyes_MAT1}
                        skeleton={nodes.Boy01_Eyes_Geo.skeleton}
                    />
                    <skinnedMesh name="h_Geo" geometry={nodes.h_Geo.geometry} material={materials.Boy01_Mouth_MAT1} skeleton={nodes.h_Geo.skeleton} />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/models/playerModels/aj.glb');
