/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useBox } from '@react-three/cannon';
import { useGLTF } from '@react-three/drei';

export const Stool = (props) => {
    const scale = 0.03;
    const [stoolRef] = useBox(() => ({
        mass: 1,
        type: 'Static',
        args: [0.5, scale * 80, 0.5],
        material: {
            friction: 1,
            restitution: 0,
        },
        rotation: [0, 0, 0],
        ...props,
    }));

    const { nodes, materials } = useGLTF('/models/props/stool.glb');
    return (
        <group ref={stoolRef} {...props} dispose={null} scale={scale}>
            <mesh geometry={nodes.stool.geometry} material={materials.stool} rotation={[Math.PI / 2, 0, 15]} />
        </group>
    );
};

useGLTF.preload('/models/props/stool.glb');
