/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/* eslint-disable react/prop-types */
import React, { useRef, useEffect, useMemo } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils';

export default function Model({ ...props }) {
    const group = useRef();
    const { scene, materials, animations } = useGLTF('/models/playerModels/whiteclown_n_hallin.glb');
    const clones = useMemo(() => clone(scene), [scene]);
    const { nodes } = useGraph(clones);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        actions.StandingIdle.play();
        group.current.position.y -= 0.45;
    }, []);
    return (
        <group ref={group} position={props.position} dispose={null}>
            <group name="Scene">
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <primitive object={nodes.Hips} />
                    <skinnedMesh
                        name="WhiteClown"
                        geometry={nodes.WhiteClown.geometry}
                        material={materials['WhiteClown_material.001']}
                        skeleton={nodes.WhiteClown.skeleton}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/models/playerModels/whiteclown_n_hallin.glb');
